// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2NMsGXPypwNH4Pl-Eo040U_1k_xSJXkQ',
    appId: '1:1088447951476:web:f5fab574e8d9be2d2ed721',
    messagingSenderId: '1088447951476',
    projectId: 'internship-80ac4',
    authDomain: 'internship-80ac4.firebaseapp.com',
    storageBucket: 'internship-80ac4.appspot.com',
    measurementId: 'G-BRMQYG8Z39',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPRkCKn1xEnoPBCKkrJi4C3Gva6SIVbKU',
    appId: '1:1088447951476:android:5488c5078d0cb9b62ed721',
    messagingSenderId: '1088447951476',
    projectId: 'internship-80ac4',
    storageBucket: 'internship-80ac4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPDh3FArihOvN0vViZj0RUpKkN-XkUvkk',
    appId: '1:1088447951476:ios:220cfa7885853c312ed721',
    messagingSenderId: '1088447951476',
    projectId: 'internship-80ac4',
    storageBucket: 'internship-80ac4.appspot.com',
    iosClientId: '1088447951476-t88jhpta7hgb4fe0osbtmq7866tsstum.apps.googleusercontent.com',
    iosBundleId: 'com.example.basic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPDh3FArihOvN0vViZj0RUpKkN-XkUvkk',
    appId: '1:1088447951476:ios:220cfa7885853c312ed721',
    messagingSenderId: '1088447951476',
    projectId: 'internship-80ac4',
    storageBucket: 'internship-80ac4.appspot.com',
    iosClientId: '1088447951476-t88jhpta7hgb4fe0osbtmq7866tsstum.apps.googleusercontent.com',
    iosBundleId: 'com.example.basic',
  );
}
