name: "Build and release"

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]
    
jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3


      - name: Set up Flutter 
        uses: subosito/flutter-action@v2
        with: 
          flutter-version: '2.8.0'
          channel: 'stable'
      
      - name: Change directory to basic
        run: ls

      - name: changig 
        run: cd /basic

      - name: changig 
        run: ls
        
      - name: Install Dependencies 
        run: flutter pub get 

      - name: Build APK
        run: flutter build apk --release

      - name: Build AppBundle
        run: flutter build appbundle 

      - name: Build IPA 
        run: flutter build ipa

      - name: Compress Archives and IPAs
        run: |
          cd ..
          tar -czf ios_build.tar.gz basic/build/ios

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Releases
          path: |
            basic/build/app/outputs/flutter-apk/app-release.apk
            basic/build/app/outputs/bundle/release/app-release.aab
            ios_build.tar.gz

      - name: Create Release
        uses: ncipollo/release-action@v1
        with: 
          artifacts: "basic/build/app/outputs/flutter-apk/app-release.apk, basic/build/app/outputs/bundle/release/app-release.aab, ios_build.tar.gz"
          tag: v1.0.${{github.run_number}}
          token: ${{secrets.TOKEN}}
